server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: payment_routh
          uri: lb://cloud-payment-service
#          uri: http://localhost:8001
          predicates:
            - Path=/payment/get/**
        - id: payment_routh2
          uri: lb://cloud-payment-service
#          uri: http://localhost:8001
          predicates:
            - Path=/payment/lb/**
            - After=2020-12-13T21:27:32.030+08:00[GMT+08:00]
#            - Cookie=username,zzyy
#            - Header=X-Request-Id,\d+


      discovery:
        locator:
          enabled: true

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka

